apiVersion: apps/v1
kind: Deployment

metadata:
  name: media-api

spec:
  replicas: 3

  selector:
    matchLabels:
      app: media-api

  template:
    metadata:
      labels:
        app: media-api

    spec:
      containers:
        - name: media-api
          image: media-api:v2
          ports:
            - containerPort: 8080
