apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-worker
  template:
    metadata:
      labels:
        app: media-worker
    spec:
      containers:
        - name: media-worker
          image: media-worker:v4
